### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by dscho** [fiji/Time_Lapse#1]
- [x] No of waves over time
- [x] Wavelengths over time
- [x] Configure Gauss sigma, sigma 0/1, x 0/1
- [x] Compensate for phase jump (2 PI)
- [x] Clean up code/commits

**Comment by dscho** [comment]
@djoerg I updated the code a bit. Unfortunately, there seems to be a black stripe on the left; I will investigate what causes this, most likely a stupid mistake while refactoring.

Please note that after synchronizing your local copy, the `main` method moved from `Phase_Map` into `PhaseMapTestDrive`. I was just trying to separate test code from production code better: there is no need to ship test code to end users.

I have to admit that I struggle a bit with the parameters; the test image seems to have much narrower bands than I am used to, and the wavelet transform finds much longer phases than are actually there. Maybe you could have a look?

**Comment by soroldon** [comment]
do we need another jam session @geekmountain? i'm still here till the 26th

**Comment by dscho** [comment]
> Unfortunately, there seems to be a black stripe on the left

I just fixed this in 44d8e16363c0e680a7e6940480552382f7500153.

> do we need another jam session @geekmountain?

We connected via Skype, it was quicker. But do remember: Sonntag is Masstag.

**Comment by dscho** [comment]
@soroldon how can we connect for testing?

**Comment by soroldon** [comment]
ich bin extra eingeflogen und sitz im 4.stock!
bin heute leider ein bissl busy. morgen?

**Comment by dscho** [comment]
> morgen?

Sir, you got yourself a date.

**Comment by soroldon** [comment]
passt, Uhrzeit?

**Comment by dscho** [comment]
> Uhrzeit?

9, atrium?

**Comment by soroldon** [comment]
Passt
