### ISSUE TITLE
Respect calibration

### ISSUE THREAD

**Issue by soroldon** [fiji/Time_Lapse#2]
The plots should respect the calibration both in x (mm, pixels?) and in the phase (ticks should be at -PI `* n`), and mention the unit in the x axis label.

**Comment by ctrueden** [comment]
Unfortunately, no one is actively adding new features to this plugin at the moment. But pull requests are very welcome!

**Comment by dscho** [comment]
No worries, @soroldon and I are working on this together. This is not Yet Another Project You're Stuck With.

**Comment by ctrueden** [comment]
@dscho Awesome, thanks for your help!

**Comment by dscho** [comment]
@ctrueden actually, it is not my "help". This _is_ my project.

**Comment by ctrueden** [comment]
I am glad you still feel ownership over some ImageJ- and Fiji-related projects. The documentation needs to be clearer about who is formally responsible for maintaining each component of the SciJava software stack. I would like to differentiate between "active" and "minimal" maintenance, similar to [how Drupal does it](https://www.drupal.org/node/1066982). As such, it would be very helpful to have a formal list of which components you still consider yourself to be maintaining (both actively and minimally).

I filed issue fiji/fiji#121 to track this.

**Comment by dscho** [comment]
Thanks, but I am here to code, not to do more bureaucracy...

**Comment by ctrueden** [comment]
The point is not bureaucracy, but expectation management. The community needs guidance on what to expect for each project. Will PRs be merged? Under what conditions? By whom? Certainly as a core maintainer, I need to know who, if anyone, is handling issues and PRs for each component. Since you are only "here to code" then it seems you are not taking ownership any more after all, which is too bad.

**Comment by dscho** [comment]
> it seems you are not taking ownership any more

It was not exactly my choice to have ownership ripped from me. As you know very well, if I truly had ownership, certain obsolete components would not have been released for the very first time long after they were deprecated (but nobody gave a flying fly about that, nor about my decision), certain backwards-compatibility-breaking changes would never have entered the source code repository, let alone the update site, etc. So do not blame me, please.

**Comment by dscho** [comment]
@soroldon would you mind testing this `.jar` file (which I hope [addresses](https://github.com/fiji/Time_Lapse/commit/phase-map-calibrated) this ticket)? https://github.com/fiji/Time_Lapse/releases/download/test-phase-map/Time_Lapse-2.0.2-SNAPSHOT.jar

**Comment by soroldon** [comment]
looks great!
how laborious would it be to highlight/emphasize the median, let say by a slightly stronger line width?
great work.

**Comment by dscho** [comment]
> looks great!

Cool!

> how laborious would it be to highlight/emphasize the median, let say by a slightly stronger line width?

Not laborious at all: https://github.com/fiji/Time_Lapse/releases/download/test-phase-map/Time_Lapse-2.0.2-SNAPSHOT.jar

**Comment by soroldon** [comment]
Schaut super aus.

**Comment by dscho** [comment]
Cool. Then I should merge it today.

**Comment by dscho** [comment]
I just merged it.

**Comment by dscho** [comment]
@soroldon you can get the newest version from http://jenkins.imagej.net/job/Time_Lapse/ now, since I merged it into our main development branch (which is called `master` with Git/GitHub).

**Comment by soroldon** [comment]
yo,

kurze frage: welches der java jars brauch ich denn jetzt? das letzte mit ~74kb?

**Comment by dscho** [comment]
Yep, sorry, I should have made clear that you need this one: http://jenkins.imagej.net/job/Time_Lapse/lastSuccessfulBuild/artifact/target/Time_Lapse-2.0.2-SNAPSHOT.jar

**Comment by soroldon** [comment]
Subba
